-- The map a replay of logs/session-teekywiki-2026-09-26T16-13-38.log has built
-- by line 4147, just before the s from labyrinth-289. Generated, not written:
-- see labyrinth_level_5_closure_spec.lua for how and when to regenerate it.
BEGIN;
INSERT INTO areas(id,slug,name) VALUES(1,'labyrinth-level-1','The Labyrinth, Level 1');
INSERT INTO areas(id,slug,name) VALUES(2,'labyrinth-level-5','The Labyrinth, Level 5');
INSERT INTO areas(id,slug,name) VALUES(3,'labyrinth-level-4','The Labyrinth, Level 4');
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(204,'labyrinth-203','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. The only exit is to the east.',2,'2026-09-27T11:43:22',2,0,0,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(205,'labyrinth-204','labyrinth','You have entered a small room with a with a stone staircase in the center. The staircase leads upward. You can also exit to the south and west.',2,'2026-09-27T11:43:26',3,1,0,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(206,'labyrinth-205','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are north, south, and west.',2,'2026-09-27T11:43:31',4,1,-1,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(207,'labyrinth-206','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are east and west.',2,'2026-09-27T11:43:35',4,0,-1,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(208,'labyrinth-207','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are north, east, and south.',2,'2026-09-27T11:43:39',4,-1,-1,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(209,'labyrinth-208','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. The only exit is to the north.',2,'2026-09-27T11:43:43',1,-1,-2,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(210,'labyrinth-209','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are north, west, and east.',2,'2026-09-27T11:43:48',3,1,-2,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(211,'labyrinth-210','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are south and west.',2,'2026-09-27T11:43:53',2,2,-2,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(212,'labyrinth-211','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are north and west.',2,'2026-09-27T11:43:57',2,2,-3,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(213,'labyrinth-212','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are east and west.',2,'2026-09-27T11:44:01',2,1,-3,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(214,'labyrinth-213','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are east and west.',2,'2026-09-27T11:44:06',2,0,-3,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(215,'labyrinth-214','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are east and west.',2,'2026-09-27T11:44:11',2,-1,-3,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(216,'labyrinth-215','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are north and east.',2,'2026-09-27T11:44:15',2,-2,-3,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(217,'labyrinth-216','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are north and south.',2,'2026-09-27T11:44:20',2,-2,-2,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(218,'labyrinth-217','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are north and south.',2,'2026-09-27T11:44:24',2,-2,-1,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(219,'labyrinth-218','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are north and south.',2,'2026-09-27T11:44:29',2,-2,0,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(220,'labyrinth-219','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are north and south.',2,'2026-09-27T11:44:34',2,-2,1,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(221,'labyrinth-220','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are east and south.',2,'2026-09-27T11:44:39',2,-2,2,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(222,'labyrinth-221','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are north, west, and east.',2,'2026-09-27T11:44:44',2,-1,2,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(223,'labyrinth-222','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are north and south.',2,'2026-09-27T11:44:46',1,-1,3,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(224,'labyrinth-223','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are east, south, and west.',2,'2026-09-27T11:44:52',2,-1,4,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(225,'labyrinth-224','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are north, east, and south.',2,'2026-09-27T11:44:57',2,-2,4,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(226,'labyrinth-225','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. The only exit is to the north.',2,'2026-09-27T11:45:02',1,-2,3,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(227,'labyrinth-226','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are east and west.',2,'2026-09-27T11:45:07',1,0,4,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(228,'labyrinth-227','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are east and west.',2,'2026-09-27T11:45:12',1,1,4,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(229,'labyrinth-228','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are north, south, and west.',2,'2026-09-27T11:45:17',1,2,4,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(230,'labyrinth-229','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are south and west.',2,'2026-09-27T11:45:22',1,2,5,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(231,'labyrinth-230','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are north, west, and east.',2,'2026-09-27T11:45:27',1,1,5,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(232,'labyrinth-231','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are east and south.',2,'2026-09-27T11:45:30',1,1,6,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(233,'labyrinth-232','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are east and west.',2,'2026-09-27T11:45:36',1,2,6,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(234,'labyrinth-233','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are east, south, and west.',2,'2026-09-27T11:45:41',1,3,6,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(235,'labyrinth-234','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are south and west.',2,'2026-09-27T11:45:47',1,4,6,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(236,'labyrinth-235','labyrinth','You have entered a small room with a with a stone staircase in the center. The staircase leads downward. You can also exit to the north and west. You''re hungry. You''re hungry. st Race:         Goblin Class:        Blackguard Level:        20 Experience:   18325713 Rune:         Violet Intellect:    9 Knowledge:    20 Physique:     25 Stamina:      26 Agility:      35 Charisma:     15 Mana:         0 / 0 Vitality:     1252 / 1393 Status:       Hungry Armor Rating: 21 Weapon:       Twin Katanas Armor:        Charred Chain Mail Encumberance: 1108 / 1250 x Exiting Tele-Arena... << hit return >> ┌────────────────────────────────────────────────────────────────┐ │                        Saturn V ßßδ                            │ └────────────────────────────────────────────────────────────────┘ ├─┼──┼▄│1│ Tournament Lord├──┼──┼──┼──┼──┼──┼──┼▄│#│ Who''s Online┼──┼──┼──┼──┼─┤ ├─┼──┼█│2│ The Rose - Council of Guardians──┼──┼█│''│ <message> Global Chat┼──┼─┤ ├─┼──┼█│3│ iNFinITY CoMpLeX──┼──┼──┼──┼──┼──┼──┼█│T│ Teleconference─┼──┼──┼──┼─┤ ├─┼──┼█│4│ MajorMUD─┼──┼──┼──┼──┼──┼──┼──┼──┼──┼█│ │ ────────────┼──┼──┼──┼──┼─┤ ├─┼──┼█│5│ Tele-Arena 5.6g├──┼──┼──┼──┼──┼──┼──┼█│F│ Farwest Trivia─┼──┼──┼──┼─┤ ├─┼──┼█│6│ Wheel of Fame──┼──┼──┼──┼──┼──┼──┼──┼█│I│ Internet Relay Chat──┼──┼─┤ ├─┼──┼█│7│ World Conquest─┼──┼──┼──┼──┼──┼──┼──┼█│R│ Registry of Users─┼──┼──┼─┤ ├─┼──┼█│8│ Distant Realms─┼──┼──┼──┼──┼──┼──┼──┼█│E│ Edit User Info─┼──┼──┼──┼─┤ ├─┼──┼█│9│ Mutants──┼──┼──┼──┼──┼──┼──┼──┼──┼──┼█│M│ Messages────┼──┼──┼──┼──┼─┤ ├─┼──┼█│0│ Swords of Chaos├──┼──┼──┼──┼──┼──┼──┼█│A│ SysOp Menu──┼──┼──┼─ ─┼──┼─┤ ├─┼──┼█│L│ Galactic Empire┼──┼──┼──┼──┼──┼──┼──┼█│X│ Log Off──┼──┼──┼──┼──┼──┼─┤ ├─┼──┼█│G│ More Games!─┼──┼──┼──┼──┼──┼──┼──┼──┼█│;?│ Global Help┼──┼──┼──┼──┼─┤ └─┼──┼█│B│─Trade Wars 2002┼──┼──┼──┼──┼──┼──┼──┼▀▀┼──┼──┼──┼──┼──┼──┼──┼──┼──┼─┘ └──┴▀▀┴──┴──┴──┴──┴──┴──┴──┴──┴──┴──┴──┴──┴──┴──┴──┴──┴──┴──┴──┴──┴──┴──┴──┘ ■ Users online: 2 ■ Connected for 10 minutes ■ ■ 16:16:46 ■ 24-SEP-26 ■ Command ■ : 5 Entering Tele-Arena... You''re in a labyrinth. st Race:         Goblin Class:        Blackguard Level:        20 Experience:   18325713 Rune:         Violet Intellect:    9 Knowledge:    20 Physique:     25 Stamina:      26 Agility:      35 Charisma:     15 Mana:         0 / 0 Vitality:     1252 / 1393 Status:       Hungry Armor Rating: 21 Weapon:       Twin Katanas Armor:        Charred Chain Mail Encumberance: 1108 / 1250 i You are carrying 2992 gold crowns, a soulstone, a coil of rope, a waterskin(0), a glowstone, a verbena potion, a zarynthium potion, a zarynthium potion, a verbena potion, a zarynthium potion, a heartstone, and a rue potion.',2,'2026-09-27T11:45:52',1,4,5,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(237,'labyrinth-236','labyrinth','You have entered a small room with a with a stone staircase in the center. The staircase leads downward. You can also exit to the north.',3,'2026-09-27T11:45:59',1,1,0,1,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(238,'labyrinth-237','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are north and south.',2,'2026-09-27T11:46:06',2,-1,0,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(239,'labyrinth-238','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are east and south.',2,'2026-09-27T11:46:11',2,-1,1,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(240,'labyrinth-239','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are east and west.',2,'2026-09-27T11:46:17',2,0,1,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(241,'labyrinth-240','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are east and west.',2,'2026-09-27T11:46:22',2,1,1,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(242,'labyrinth-241','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are east, south, and west.',2,'2026-09-27T11:46:28',4,2,1,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(243,'labyrinth-242','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are north and south.',2,'2026-09-27T11:46:34',4,2,0,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(244,'labyrinth-243','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are north and east.',2,'2026-09-27T11:46:39',4,2,-1,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(245,'labyrinth-244','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are east and west.',2,'2026-09-27T11:46:45',5,3,-1,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(246,'labyrinth-245','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are north, south, and west.',2,'2026-09-27T11:46:51',4,4,-1,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(247,'labyrinth-246','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are north and west.',2,'2026-09-27T11:46:57',2,4,-2,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(248,'labyrinth-247','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. The only exit is to the east.',2,'2026-09-27T11:47:02',1,3,-2,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(249,'labyrinth-248','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are south and west.',2,'2026-09-27T11:47:08',2,4,0,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(250,'labyrinth-249','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. The only exit is to the east.',2,'2026-09-27T11:47:14',1,3,0,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(251,'labyrinth-250','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are east and west.',2,'2026-09-27T11:47:21',2,3,1,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(252,'labyrinth-251','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are east and west.',2,'2026-09-27T11:47:27',2,4,1,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(253,'labyrinth-252','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are south and west.',2,'2026-09-27T11:47:33',2,5,1,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(254,'labyrinth-253','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are north and east.',2,'2026-09-27T11:47:39',2,5,0,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(255,'labyrinth-254','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are south and west.',2,'2026-09-27T11:47:45',2,6,0,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(256,'labyrinth-255','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are north and south.',2,'2026-09-27T11:47:51',2,6,-1,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(257,'labyrinth-256','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are north and west.',2,'2026-09-27T11:47:57',2,6,-2,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(258,'labyrinth-257','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are north, east, and south.',2,'2026-09-27T11:48:03',3,5,-2,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(259,'labyrinth-258','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are north, west, and east.',2,'2026-09-27T11:48:09',3,5,-3,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(260,'labyrinth-259','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are east and west.',2,'2026-09-27T11:48:16',2,4,-3,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(261,'labyrinth-260','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. The only exit is to the east.',2,'2026-09-27T11:48:22',1,3,-3,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(262,'labyrinth-261','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are east and west.',2,'2026-09-27T11:48:28',2,6,-3,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(263,'labyrinth-262','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are north and west.',2,'2026-09-27T11:48:35',2,7,-3,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(264,'labyrinth-263','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are north and south.',2,'2026-09-27T11:48:41',2,7,-2,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(265,'labyrinth-264','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are north and south.',2,'2026-09-27T11:48:48',3,7,-1,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(266,'labyrinth-265','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are north and south.',2,'2026-09-27T11:48:55',2,7,0,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(267,'labyrinth-266','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are south and west.',2,'2026-09-27T11:49:02',2,7,1,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(268,'labyrinth-267','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. The only exit is to the east.',2,'2026-09-27T11:49:08',1,6,1,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(269,'labyrinth-268','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. The only exit is to the south.',2,'2026-09-27T11:49:16',1,5,-1,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(270,'labyrinth-269','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. The only exit is to the east.',2,'2026-09-27T11:49:25',1,0,-2,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(271,'labyrinth-270','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are north, west, and east.',2,'2026-09-27T11:49:33',1,0,2,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(272,'labyrinth-271','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are east and west.',2,'2026-09-27T11:49:38',1,1,2,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(273,'labyrinth-272','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are north, west, and east.',2,'2026-09-27T11:49:46',1,2,2,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(274,'labyrinth-273','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are north, west, and east.',2,'2026-09-27T11:49:50',2,3,2,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(275,'labyrinth-274','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. The only exit is to the west.',2,'2026-09-27T11:49:55',1,4,2,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(276,'labyrinth-275','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are north, east, and south.',2,'2026-09-27T11:50:03',1,3,3,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(277,'labyrinth-276','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are north, east, and south.',2,'2026-09-27T11:50:10',1,3,4,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(278,'labyrinth-277','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are east and west.',2,'2026-09-27T11:50:17',1,4,4,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(279,'labyrinth-278','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are north, south, and west.',2,'2026-09-27T11:50:24',1,5,4,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(280,'labyrinth-279','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are north, east, and south.',2,'2026-09-27T11:50:32',1,5,3,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(281,'labyrinth-280','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are north, west, and east.',2,'2026-09-27T11:50:36',2,6,3,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(282,'labyrinth-281','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are south and west.',2,'2026-09-27T11:50:42',2,7,3,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(283,'labyrinth-282','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are north and west.',2,'2026-09-27T11:50:45',2,7,2,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(284,'labyrinth-283','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. You notice a small, round stone protruding from the wall. The only exit is to the east.',2,'2026-09-27T11:50:53',1,6,2,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(285,'labyrinth-284','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are east and south.',2,'2026-09-27T11:51:00',1,6,4,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(286,'labyrinth-285','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are north and west.',2,'2026-09-27T11:51:07',1,7,4,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(287,'labyrinth-286','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are north, south, and west.',2,'2026-09-27T11:51:14',1,7,5,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(288,'labyrinth-287','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are south and west.',2,'2026-09-27T11:51:19',1,7,6,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(289,'labyrinth-288','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are east and west.',2,'2026-09-27T11:51:22',1,6,6,0,NULL);
INSERT INTO rooms(id,slug,name,description,area_id,first_visited,visits,x,y,z,trap) VALUES(290,'labyrinth-289','labyrinth','You are nearly lost in a complexity of caverns deeper than anything you have ever experienced. The dark chambers disorient you as you pick your way through them. Exits are east and south.',2,'2026-09-27T11:51:31',1,5,6,0,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(204,'e',205,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(205,'s',206,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(205,'u',237,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(205,'w',204,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(206,'n',205,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(206,'s',210,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(206,'w',207,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(207,'e',206,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(207,'w',208,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(208,'e',207,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(208,'n',238,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(208,'s',209,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(209,'n',208,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(210,'e',211,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(210,'n',206,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(210,'w',270,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(211,'s',212,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(211,'w',210,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(212,'n',211,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(212,'w',213,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(213,'e',212,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(213,'w',214,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(214,'e',213,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(214,'w',215,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(215,'e',214,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(215,'w',216,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(216,'e',215,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(216,'n',217,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(217,'n',218,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(217,'s',216,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(218,'n',219,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(218,'s',217,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(219,'n',220,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(219,'s',218,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(220,'n',221,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(220,'s',219,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(221,'e',222,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(221,'s',220,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(222,'e',271,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(222,'n',223,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(222,'w',221,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(223,'n',224,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(223,'s',222,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(224,'e',227,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(224,'s',223,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(224,'w',225,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(225,'e',224,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(225,'n',NULL,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(225,'s',226,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(226,'n',225,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(227,'e',228,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(227,'w',224,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(228,'e',229,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(228,'w',227,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(229,'n',230,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(229,'s',NULL,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(229,'w',228,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(230,'s',229,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(230,'w',231,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(231,'e',230,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(231,'n',232,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(231,'w',NULL,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(232,'e',233,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(232,'s',231,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(233,'e',234,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(233,'w',232,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(234,'e',235,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(234,'s',NULL,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(234,'w',233,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(235,'s',236,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(235,'w',234,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(236,'n',235,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(237,'d',205,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(237,'n',NULL,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(238,'n',239,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(238,'s',208,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(239,'e',240,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(239,'s',238,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(240,'e',241,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(240,'w',239,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(241,'e',242,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(241,'w',240,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(242,'e',251,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(242,'s',243,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(242,'w',241,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(243,'n',242,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(243,'s',244,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(244,'e',245,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(244,'n',243,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(245,'e',246,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(245,'w',244,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(246,'n',249,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(246,'s',247,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(246,'w',245,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(247,'n',246,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(247,'w',248,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(248,'e',247,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(249,'s',246,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(249,'w',250,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(250,'e',249,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(251,'e',252,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(251,'w',242,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(252,'e',253,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(252,'w',251,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(253,'s',254,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(253,'w',252,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(254,'e',255,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(254,'n',253,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(255,'s',256,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(255,'w',254,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(256,'n',255,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(256,'s',257,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(257,'n',256,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(257,'w',258,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(258,'e',257,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(258,'n',269,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(258,'s',259,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(259,'e',262,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(259,'n',258,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(259,'w',260,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(260,'e',259,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(260,'w',261,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(261,'e',260,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(262,'e',263,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(262,'w',259,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(263,'n',264,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(263,'w',262,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(264,'n',265,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(264,'s',263,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(265,'n',266,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(265,'s',264,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(266,'n',267,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(266,'s',265,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(267,'s',266,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(267,'w',268,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(268,'e',267,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(269,'s',258,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(270,'e',210,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(271,'e',272,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(271,'n',NULL,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(271,'w',222,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(272,'e',273,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(272,'w',271,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(273,'e',274,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(273,'n',NULL,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(273,'w',272,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(274,'e',275,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(274,'n',276,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(274,'w',273,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(275,'w',274,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(276,'e',NULL,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(276,'n',277,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(276,'s',274,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(277,'e',278,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(277,'n',NULL,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(277,'s',276,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(278,'e',279,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(278,'w',277,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(279,'n',NULL,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(279,'s',280,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(279,'w',278,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(280,'e',281,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(280,'n',279,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(280,'s',NULL,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(281,'e',282,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(281,'n',285,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(281,'w',280,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(282,'s',283,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(282,'w',281,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(283,'n',282,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(283,'w',284,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(284,'e',283,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(285,'e',286,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(285,'s',281,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(286,'n',287,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(286,'w',285,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(287,'n',288,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(287,'s',286,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(287,'w',NULL,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(288,'s',287,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(288,'w',289,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(289,'e',288,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(289,'w',290,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(290,'e',289,NULL,NULL,NULL);
INSERT INTO room_exits(from_id,direction,to_id,lock_key,lock_door,sealed_by) VALUES(290,'s',NULL,NULL,NULL,NULL);
COMMIT;
